apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb/metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.5
    helm:
      releaseName: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
