# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: proxmox
#   namespace: traefik-system
#
# spec:
#   entryPoints:
#     - websecure
#
#   routes:
#   - match: Host(`proxmox.local.grieco.me`)
#     kind: Rule
#     services:
#     - name: proxmox-external-svc
#       port: 8006
#
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: proxmox-external-svc
#   namespace: traefik-system
# spec:
#   externalName: https://10.13.13.2
#   type: ExternalName
