globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik-external

ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    http3:
      enabled: true
    advertisedPort: 4443
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowCrossNamespace: true
    publishedService:
      enabled: false
  file:
    # -- Create a file provider
    enabled: true
    # -- Allows Traefik to automatically watch for file changes
    watch: true
    # -- File content (YAML format, go template supported) (see https://doc.traefik.io/traefik/providers/file/)
    content: |
      http:
        #region routers
        routers:
          proxmox:
            entryPoints:
              - "websecure"
            rule: "Host(`proxmox.local.grieco.me`)"
            middlewares:
              - default-headers
              - https-redirectscheme
            tls: {}
            service: proxmox
          pfsense:
            entryPoints:
              - "websecure"
            rule: "Host(`pfsense.local.grieco.me`)"
            middlewares:
              - default-headers
              - https-redirectscheme
            tls: {}
            service: pfsense
          truenas:
            entryPoints:
              - "websecure"
            rule: "Host(`truenas.local.grieco.me`)"
            middlewares:
              - default-headers
              - https-redirectscheme
            tls: {}
            service: truenas
          nextcloud:
            entryPoints:
              - "websecure"
            rule: "Host(`nextcloud.local.grieco.me`)"
            middlewares:
              - default-headers
              - https-redirectscheme
            tls: {}
            service: nextcloud
        #endregion

        #region services
        services:
          proxmox:
            loadBalancer:
              servers:
                - url: "https://10.13.13.2:8006"
              passHostHeader: true
          pfsense:
            loadBalancer:
              servers:
                - url: "https://10.13.13.1:10443"
              passHostHeader: true
          truenas:
            loadBalancer:
              servers:
                - url: "https://10.13.13.3"
              passHostHeader: true
          nextcloud:
            loadBalancer:
              servers:
                - url: "https://10.13.13.3:9001"
              passHostHeader: true
        #endregion

        middlewares:
          https-redirect:
            redirectScheme:
              scheme: https
          https-redirectscheme:
            redirectScheme:
              scheme: https
              permanent: true
          default-headers:
            headers:
              frameDeny: true
              browserXssFilter: true
              contentTypeNosniff: true
              forceSTSHeader: true
              stsIncludeSubdomains: true
              stsPreload: true
              stsSeconds: 15552000
              customFrameOptionsValue: SAMEORIGIN
              customRequestHeaders:
                X-Forwarded-Proto: https

          secured:
            chain:
              middlewares:
              - default-whitelist
              - default-headers

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    # 10.2.0.192/26
    loadBalancerIP: 10.2.0.249
  loadBalancerSourceRanges: []
  externalIPs: []
