apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-grieco-me
  namespace: pihole-system
spec:
  secretName: local-grieco-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.grieco.me"
  dnsNames:
  - "local.grieco.me"
  - "*.local.grieco.me"
